site:
  title: Eclipse Scout
  start_page: scout-docs:ROOT:index.adoc
content:
  sources:
  - url: ./../..
    branches: releases/22.0, releases/23.1, releases/23.2
    start_path: docs
ui:
  bundle:
    url: ./eclipse-scout-ui-bundle.zip
    snapshot: true
antora:
  extensions:
  - require: '@antora/lunr-extension'
    languages: [en]
