site:
  title: Eclipse Scout
  start_page: scout-docs:eclipse-help:scout_user_guide.adoc
content:
  sources:
  - url: ./../..
    branches: releases/24.1
    start_path: docs
ui:
  bundle:
    url: ./eclipse-help-ui-bundle.zip
    snapshot: true
